services:
  api:
    build:
      context: .
      target: prod
    image: saag-api
    container_name: saag-api
    ports:
      - "8000:8000"

  web:
    build:
      context: ./web
      target: prod
    image: saag-web
    container_name: saag-web
    ports:
      - "3000:3000"
