services:
  api:
    build:
      context: .
      target: dev
    image: saag-api:dev
    container_name: saag-api-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  web:
    build:
      context: ./web
      target: dev
    image: saag-web:dev
    container_name: saag-web-dev
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
